//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BitMagEntities : DbContext
    {
        public BitMagEntities()
            : base("name=BitMagEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<КатегорияТовара> КатегорияТовара { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставки> Поставки { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Продажи> Продажи { get; set; }
        public virtual DbSet<Производитель> Производитель { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
        public virtual DbSet<ПоставкиТовара> ПоставкиТовара { get; set; }
        public virtual DbSet<Продажи_Товара> Продажи_Товара { get; set; }
    }
}
