//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки
    {
        public int Код_Поставки_ПТ { get; set; }
        public Nullable<int> Код_Поставщика_ПТ { get; set; }
        public Nullable<System.DateTime> ДатаПоставки { get; set; }
    
        public virtual Поставщик Поставщик { get; set; }
        public virtual ПоставкиТовара ПоставкиТовара { get; set; }
    }
}
