//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПоставкиТовара
    {
        public int КодПоставки { get; set; }
        public Nullable<int> КодКат_Товара { get; set; }
        public Nullable<int> КодТовара { get; set; }
        public Nullable<int> Кол_во { get; set; }
    
        public virtual Поставки Поставки { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
