//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи
    {
        public int Код_Продажи_П { get; set; }
        public Nullable<System.DateTime> Дата_Продажи_П { get; set; }
        public Nullable<int> Код_Продовца_П { get; set; }
        public Nullable<int> Код_Клиента_П { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Продажи_Товара Продажи_Товара { get; set; }
    }
}
