//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_Продажи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Т_Продажи()
        {
            this.Т_Продажи_Товара = new HashSet<Т_Продажи_Товара>();
        }
    
        public int Код_Продажи_П { get; set; }
        public Nullable<System.DateTime> Дата_Продажи_П { get; set; }
        public Nullable<int> Код_Продовца_П { get; set; }
        public Nullable<int> Код_Клиента_П { get; set; }
    
        public virtual Т_Клиенты Т_Клиенты { get; set; }
        public virtual Т_Сотрудники Т_Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Т_Продажи_Товара> Т_Продажи_Товара { get; set; }
    }
}
