//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_Продажи_Товара
    {
        public int Код_Продажи { get; set; }
        public Nullable<int> Код_Катег { get; set; }
        public Nullable<int> Код_Товара { get; set; }
        public Nullable<int> Кол_во { get; set; }
        public int Код { get; set; }
    
        public virtual Т_Продажи Т_Продажи { get; set; }
        public virtual Т_Товар Т_Товар { get; set; }
    }
}
