//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_КатегорияТовара
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Т_КатегорияТовара()
        {
            this.Т_Товар = new HashSet<Т_Товар>();
        }
    
        public int Код_Кат { get; set; }
        public string Кат_Товара { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Т_Товар> Т_Товар { get; set; }
    }
}
