//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_Поставки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Т_Поставки()
        {
            this.Т_ПоставкиТовара = new HashSet<Т_ПоставкиТовара>();
        }
    
        public int Код_Поставки_ПТ { get; set; }
        public Nullable<int> Код_Поставщика_ПТ { get; set; }
        public Nullable<System.DateTime> ДатаПоставки { get; set; }
    
        public virtual Т_Поставщик Т_Поставщик { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Т_ПоставкиТовара> Т_ПоставкиТовара { get; set; }
    }
}
