//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Т_Сотрудники()
        {
            this.Т_Продажи = new HashSet<Т_Продажи>();
        }
    
        public int Код_Сотрудника { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> Код_Должности { get; set; }
    
        public virtual Т_Должность Т_Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Т_Продажи> Т_Продажи { get; set; }
    }
}
