//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Т_Товар()
        {
            this.Т_ПоставкиТовара = new HashSet<Т_ПоставкиТовара>();
            this.Т_Продажи_Товара = new HashSet<Т_Продажи_Товара>();
        }
    
        public int Код_Товара_Т { get; set; }
        public string Товар_Т { get; set; }
        public Nullable<int> Код_КатТовара_Т { get; set; }
        public Nullable<int> Код_Производителя_Т { get; set; }
        public string Изображение_Т { get; set; }
        public Nullable<decimal> Цена_Закупочная_Т { get; set; }
        public Nullable<decimal> Цена_Реализации_Т { get; set; }
        public Nullable<System.DateTime> ДатаВыпуска { get; set; }
        public Nullable<short> Гарантия { get; set; }
        public Nullable<int> Кол_во_Т { get; set; }
    
        public virtual Т_КатегорияТовара Т_КатегорияТовара { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Т_ПоставкиТовара> Т_ПоставкиТовара { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Т_Продажи_Товара> Т_Продажи_Товара { get; set; }
        public virtual Т_Производитель Т_Производитель { get; set; }
    }
}
