//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Appliance_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.ПоставкиТовара = new HashSet<ПоставкиТовара>();
            this.Продажи_Товара = new HashSet<Продажи_Товара>();
        }
    
        public int Код_Товара_Т { get; set; }
        public string Товар_Т { get; set; }
        public Nullable<int> Код_КатТовара_Т { get; set; }
        public Nullable<int> Код_Производителя_Т { get; set; }
        public byte[] Изображение_Т { get; set; }
        public Nullable<decimal> Цена_Закупочная_Т { get; set; }
        public Nullable<decimal> Цена_Реализации_Т { get; set; }
        public Nullable<System.DateTime> ДатаВыпуска { get; set; }
        public Nullable<short> Гарантия { get; set; }
        public Nullable<int> Кол_во_Т { get; set; }
    
        public virtual КатегорияТовара КатегорияТовара { get; set; }
        public virtual Производитель Производитель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПоставкиТовара> ПоставкиТовара { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи_Товара> Продажи_Товара { get; set; }
    }
}
